In [1]:
import pandas as pd

In [3]:
nuclear = pd.read_csv("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/boot/nuclear.csv")

In [5]:
nuclear

    rownames    cost   date  t1  t2   cap  pr  ne  ct  bw  cum.n  pt
0          1  460.05  68.58  14  46   687   0   1   0   0     14   0
1          2  452.99  67.33  10  73  1065   0   0   1   0      1   0
2          3  443.22  67.33  10  85  1065   1   0   1   0      1   0
3          4  652.32  68.00  11  67  1065   0   1   1   0     12   0
4          5  642.23  68.00  11  78  1065   1   1   1   0     12   0
5          6  345.39  67.92  13  51   514   0   1   1   0      3   0
6          7  272.37  68.17  12  50   822   0   0   0   0      5   0
7          8  317.21  68.42  14  59   457   0   0   0   0      1   0
8          9  457.12  68.42  15  55   822   1   0   0   0      5   0
9         10  690.19  68.33  12  71   792   0   1   1   1      2   0
10        11  350.63  68.58  12  64   560   0   0   0   0      3   0
11        12  402.59  68.75  13  47   790   0   1   0   0      6   0
12        13  412.18  68.42  15  62   530   0   0   1   0      2   0
13        14  495.58  68.92  17  52  1050   0   0   0   0      7   0
14        15  394.36  68.92  13  65   850   0   0   0   1     16   0
15        16  423.32  68.42  11  67   778   0   0   0   0      3   0
16        17  712.27  69.50  18  60   845   0   1   0   0     17   0
17        18  289.66  68.42  15  76   530   1   0   1   0      2   0
18        19  881.24  69.17  15  67  1090   0   0   0   0      1   0
19        20  490.88  68.92  16  59  1050   1   0   0   0      8   0
20        21  567.79  68.75  11  70   913   0   0   1   1     15   0
21        22  665.99  70.92  22  57   828   1   1   0   0     20   0
22        23  621.45  69.67  16  59   786   0   0   1   0     18   0
23        24  608.80  70.08  19  58   821   1   0   0   0      3   0
24        25  473.64  70.42  19  44   538   0   0   1   0     19   0
25        26  697.14  71.08  20  57  1130   0   0   1   0     21   0
26        27  207.51  67.25  13  63   745   0   0   0   0      8   1
27        28  288.48  67.17   9  48   821   0   0   1   0      7   1
28        29  284.88  67.83  12  63   886   0   0   0   1     11   1
29        30  280.36  67.83  12  71   886   1   0   0   1     11   1
30        31  217.38  67.25  13  72   745   1   0   0   0      8   1
31        32  270.71  67.83   7  80   886   1   0   0   1     11   1

In [7]:
nuclear.cost.mean()

461.5603125

In [9]:
north_east = nuclear[nuclear["ne"] == 1]

In [17]:
len(north_east)

8

In [21]:
sorted_dates = nuclear.sort_values(by="date")
sorted_dates

    rownames    cost   date  t1  t2   cap  pr  ne  ct  bw  cum.n  pt
27        28  288.48  67.17   9  48   821   0   0   1   0      7   1
26        27  207.51  67.25  13  63   745   0   0   0   0      8   1
30        31  217.38  67.25  13  72   745   1   0   0   0      8   1
1          2  452.99  67.33  10  73  1065   0   0   1   0      1   0
2          3  443.22  67.33  10  85  1065   1   0   1   0      1   0
31        32  270.71  67.83   7  80   886   1   0   0   1     11   1
29        30  280.36  67.83  12  71   886   1   0   0   1     11   1
28        29  284.88  67.83  12  63   886   0   0   0   1     11   1
5          6  345.39  67.92  13  51   514   0   1   1   0      3   0
3          4  652.32  68.00  11  67  1065   0   1   1   0     12   0
4          5  642.23  68.00  11  78  1065   1   1   1   0     12   0
6          7  272.37  68.17  12  50   822   0   0   0   0      5   0
9         10  690.19  68.33  12  71   792   0   1   1   1      2   0
17        18  289.66  68.42  15  76   530   1   0   1   0      2   0
15        16  423.32  68.42  11  67   778   0   0   0   0      3   0
7          8  317.21  68.42  14  59   457   0   0   0   0      1   0
12        13  412.18  68.42  15  62   530   0   0   1   0      2   0
8          9  457.12  68.42  15  55   822   1   0   0   0      5   0
0          1  460.05  68.58  14  46   687   0   1   0   0     14   0
10        11  350.63  68.58  12  64   560   0   0   0   0      3   0
20        21  567.79  68.75  11  70   913   0   0   1   1     15   0
11        12  402.59  68.75  13  47   790   0   1   0   0      6   0
14        15  394.36  68.92  13  65   850   0   0   0   1     16   0
13        14  495.58  68.92  17  52  1050   0   0   0   0      7   0
19        20  490.88  68.92  16  59  1050   1   0   0   0      8   0
18        19  881.24  69.17  15  67  1090   0   0   0   0      1   0
16        17  712.27  69.50  18  60   845   0   1   0   0     17   0
22        23  621.45  69.67  16  59   786   0   0   1   0     18   0
23        24  608.80  70.08  19  58   821   1   0   0   0      3   0
24        25  473.64  70.42  19  44   538   0   0   1   0     19   0
21        22  665.99  70.92  22  57   828   1   1   0   0     20   0
25        26  697.14  71.08  20  57  1130   0   0   1   0     21   0

In [25]:
prior_site = nuclear[nuclear.pr == True]
prior_site

    rownames    cost   date  t1  t2   cap  pr  ne  ct  bw  cum.n  pt
2          3  443.22  67.33  10  85  1065   1   0   1   0      1   0
4          5  642.23  68.00  11  78  1065   1   1   1   0     12   0
8          9  457.12  68.42  15  55   822   1   0   0   0      5   0
17        18  289.66  68.42  15  76   530   1   0   1   0      2   0
19        20  490.88  68.92  16  59  1050   1   0   0   0      8   0
21        22  665.99  70.92  22  57   828   1   1   0   0     20   0
23        24  608.80  70.08  19  58   821   1   0   0   0      3   0
29        30  280.36  67.83  12  71   886   1   0   0   1     11   1
30        31  217.38  67.25  13  72   745   1   0   0   0      8   1
31        32  270.71  67.83   7  80   886   1   0   0   1     11   1

In [29]:
prior_site.cap.max()

1065